import Link from "next/link";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "portfolio website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen">
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
